### PR TITLE
Fix: python ident error

### PR DESCRIPTION
**Pull request by cpieper78**
removed blank space that was causing a python ident exception.

### CODE REVIEW

**Comment by ascodmitry** [comment]
This is causing a huge problem and needs to be approved

**Review by ascodmitry — APPROVED** [review]

**Comment by ascodmitry** [comment]
this is good to go, verified

**Review by ascodmitry — APPROVED** [review]
confirmed

**Comment by ascodmitry** [comment]
done

**Review by vsnyc — APPROVED** [review]

**Pull request merged**
